apiVersion: v1
kind: Service
metadata:
  name: subscriber-service
  namespace: educonnect
spec:
  selector:
    app: subscriber-service
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
