apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: educonnect
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']

      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:9050']

      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service:9051']

      - job_name: 'course-service'
        static_configs:
          - targets: ['course-service:9052']
      
      - job_name: 'kubelet-cadvisor'
        scheme: https
        metrics_path: /metrics/cadvisor
        kubernetes_sd_configs:
          - role: node
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_address_InternalIP]
            target_label: __address__
            replacement: $1:10250
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

