global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
