global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:5000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'course-service'
    static_configs:
      - targets: ['course-service:9052']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9051']
  
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:9050']