apiVersion: v1
kind: Service
metadata:
  name: kafka0
  namespace: educonnect
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: external
      protocol: TCP
      port: 29092
      targetPort: 29092
