apiVersion: v1
kind: ConfigMap
metadata:
  name: course-config
  namespace: educonnect
data:
  MYSQL_HOST: "mysql-coursedb"
  MYSQL_PORT: "3306"
  MYSQL_DB: "coursedb"
  MYSQL_USER: "user"
  AUTH_SERVICE_URL: "http://auth-service:9050/auth"
  ENVIRONMENT: "local"
  KAFKA_BOOTSTRAP_SERVERS_K8S: "kafka0:29092"
  KAFKA_BOOTSTRAP_SERVERS_LOCAL: "kafka0:9092"
