apiVersion: v1
kind: Service
metadata:
  name: publisher-service
  namespace: educonnect
spec:
  selector:
    app: publisher-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
