apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 9051        # porta esposta nel cluster
      targetPort: 9051  # porta del container
  type: ClusterIP